Implement Match betting
turniere/turniere-backend pull request #58
Opened 2019-06-14 17:05 UTC by Thor77

[TURNIERE-231](https://jiratinf16b4.it.dh-karlsruhe.de:8443/browse/TURNIERE-231)

2019-06-15 20:53 UTC, Malaber requested changes
I don't see a implementation for returning the bet counts for a match or something like that, is that planned for a later pr or am I blind?

2019-06-15 20:53 UTC, Malaber commented on app/services/user_service.rb
> +    raise UserServiceError, "Betting is not supported while match is #{match.state}" \
"Betting is not allowed while match is #{match.state}" would be better I think

2019-06-16 10:50 UTC, Thor77 commented
Bet counts for a match are implemented [here](https://github.com/turniere/turniere-backend/pull/58/files#diff-f68d3f57253927025ffac9998b1766e1R8)

2019-06-16 14:27 UTC, Malaber submitted a review, later dismissed

2019-06-17 11:29 UTC, Malaber submitted a review, later dismissed
lgtm

2019-06-17 12:59 UTC, Malaber approved these changes
lgtm

2019-06-17 13:00 UTC, merged